-- Education Forum 1.1.0: one-time setup for a project without app tables.
-- Run the entire file in the Supabase SQL Editor. Do not run on an existing installation.
-- Generated by node scripts/prepare-supabase.cjs; canonical sources are migrations/*.sql.

begin;

-- 001_platform.sql
-- Education Forum: apply to a fresh Supabase project.
create type public.review_status as enum ('pending','approved','rejected','changes_requested','removed');
create type public.user_role as enum ('student','teacher','tutor','creator','admin','owner');
create table public.profiles(id uuid primary key references auth.users on delete cascade, display_name text not null default '', role public.user_role not null default 'student', suspended boolean not null default false, monetization_enabled boolean not null default false, created_at timestamptz not null default now());
create function public.create_profile() returns trigger language plpgsql security definer set search_path=public as $$ begin insert into profiles(id) values(new.id); return new; end $$;
create trigger auth_profile after insert on auth.users for each row execute function public.create_profile();
create function public.is_admin() returns boolean language sql stable security definer set search_path=public as $$ select exists(select 1 from profiles where id=auth.uid() and role in ('admin','owner') and not suspended) $$;
create function public.is_active() returns boolean language sql stable security definer set search_path=public as $$ select exists(select 1 from profiles where id=auth.uid() and not suspended) $$;
create table public.entries(id uuid primary key default gen_random_uuid(),owner_id uuid not null references public.profiles,kind text not null check(kind in ('book','assistance','idea','reel','course')),title text not null check(length(trim(title))>=4),description text not null check(length(trim(description))>=20),category text not null,author text not null,level text not null default 'All levels',status public.review_status not null default 'pending',file_path text,color text not null default '#244d41',target bigint not null default 0 check(target>=0),raised bigint not null default 0 check(raised>=0),created_at timestamptz not null default now());
create index entries_discovery on public.entries(kind,status,category);
create index entries_owner on public.entries(owner_id);
-- Sensitive details are never part of the public entry projection.
create table public.application_details(entry_id uuid primary key references public.entries on delete cascade,owner_id uuid not null references public.profiles,private_details jsonb not null default '{}',supporting_paths text[] not null default '{}');
create table public.audit_log(id bigint generated always as identity primary key,actor_id uuid references public.profiles,entity_id uuid,action text not null,reason text not null,details jsonb not null default '{}',created_at timestamptz not null default now());
create table public.plans(id uuid primary key default gen_random_uuid(),name text not null,price_minor bigint not null check(price_minor>=0),currency text not null check(currency ~ '^[A-Z]{3}$'),benefits jsonb not null default '[]',active boolean not null default false,apple_product_id text,google_product_id text);
create table public.feature_rules(feature_key text primary key,access_mode text not null check(access_mode in ('free','individual','premier','subscription')),plan_id uuid references public.plans,price_minor bigint check(price_minor>=0),free_until timestamptz);
create table public.earnings_policies(id uuid primary key default gen_random_uuid(),role public.user_role not null,view_rate numeric(16,8) not null default 0 check(view_rate>=0),subscriber_rate numeric(16,8) not null default 0 check(subscriber_rate>=0),minimum_payout_minor bigint not null default 1000 check(minimum_payout_minor>=0),maximum_earning_minor bigint check(maximum_earning_minor>=0),currency text not null default 'USD',active boolean not null default false);
create table public.transactions(id uuid primary key default gen_random_uuid(),user_id uuid not null references public.profiles,purpose text not null check(purpose in ('subscription','premier','content','donation','funding','payout','refund')),amount_minor bigint not null check(amount_minor>0),currency text not null check(currency ~ '^[A-Z]{3}$'),status text not null default 'pending' check(status in ('pending','successful','failed','refunded')),provider text not null,provider_reference text unique,idempotency_key text not null unique,entry_id uuid references public.entries,created_at timestamptz not null default now());
create table public.earnings(id uuid primary key default gen_random_uuid(),user_id uuid not null references public.profiles,policy_id uuid not null references public.earnings_policies,amount_minor bigint not null check(amount_minor>=0),currency text not null,status text not null default 'pending' check(status in ('pending','approved','withdrawable','paid','rejected')),verified_views bigint not null default 0,verified_subscribers bigint not null default 0,period_start date not null,period_end date not null,unique(user_id,policy_id,period_start,period_end));
create table public.funding_agreements(id uuid primary key default gen_random_uuid(),entry_id uuid not null references public.entries,student_id uuid not null references public.profiles,stage text not null default 'review' check(stage in ('review','negotiation','agreement','funding','progress','completed','suspended')),amount_minor bigint check(amount_minor>0),currency text not null default 'USD',conditions text not null default '',progress_notes text not null default '',approved_by uuid references public.profiles,created_at timestamptz not null default now());
create table public.reports(id uuid primary key default gen_random_uuid(),entry_id uuid not null references public.entries,reporter_id uuid not null references public.profiles,reason text not null check(length(reason)>5),status text not null default 'open' check(status in ('open','reviewed','dismissed')),created_at timestamptz not null default now());
create table public.languages(id uuid primary key default gen_random_uuid(),name text not null unique,code text not null unique,active boolean not null default true);
insert into public.languages(name,code) values ('French','fr'),('Dutch','nl'),('Spanish','es');
create table public.lessons(id uuid primary key default gen_random_uuid(),language_id uuid references public.languages,title text not null,level text not null check(level in ('beginner','intermediate','advanced')),content jsonb not null,active boolean not null default false);
create table public.learning_progress(user_id uuid references public.profiles,lesson_id uuid references public.lessons,progress integer not null default 0 check(progress between 0 and 100),updated_at timestamptz not null default now(),primary key(user_id,lesson_id));
create table public.bookmarks(user_id uuid references public.profiles,entry_id uuid references public.entries,primary key(user_id,entry_id));
create table public.provider_configuration(provider text primary key,markets text[] not null default '{}',purposes text[] not null default '{}',enabled boolean not null default false);
insert into public.provider_configuration(provider) values ('apple_iap'),('google_play'),('paypal'),('ecocash'),('opay'),('swift');

-- RLS is enabled on every public table, including those with no client-write policy.
do $$ declare t text; begin foreach t in array array['profiles','entries','application_details','audit_log','plans','feature_rules','earnings_policies','transactions','earnings','funding_agreements','reports','languages','lessons','learning_progress','bookmarks','provider_configuration'] loop execute format('alter table public.%I enable row level security',t); end loop; end $$;
create policy profile_read on public.profiles for select using(id=auth.uid() or public.is_admin());
-- No client role, suspension, balance, or eligibility mutations.
create policy entries_read on public.entries for select using(status='approved' or owner_id=auth.uid() or public.is_admin());
create policy entries_submit on public.entries for insert to authenticated with check(owner_id=auth.uid() and public.is_active() and status='pending' and target=0 and raised=0 and (file_path is null or file_path like auth.uid()::text||'/%'));
create policy private_read on public.application_details for select to authenticated using(owner_id=auth.uid() or public.is_admin());
create policy private_submit on public.application_details for insert to authenticated with check(owner_id=auth.uid() and public.is_active() and exists(select 1 from entries where id=entry_id and owner_id=auth.uid() and status='pending'));
create policy audit_read on public.audit_log for select to authenticated using(public.is_admin());
create policy plans_read on public.plans for select using(active or public.is_admin());
create policy features_read on public.feature_rules for select using(true);
create policy policies_read on public.earnings_policies for select to authenticated using(public.is_admin());
create policy transactions_read on public.transactions for select to authenticated using(user_id=auth.uid() or public.is_admin());
create policy earnings_read on public.earnings for select to authenticated using(user_id=auth.uid() or public.is_admin());
create policy funding_read on public.funding_agreements for select to authenticated using(student_id=auth.uid() or public.is_admin());
create policy reports_read on public.reports for select to authenticated using(reporter_id=auth.uid() or public.is_admin());
create policy reports_submit on public.reports for insert to authenticated with check(reporter_id=auth.uid() and public.is_active() and status='open');
create policy languages_read on public.languages for select using(active or public.is_admin());
create policy lessons_read on public.lessons for select using(active or public.is_admin());
create policy progress_own on public.learning_progress for all to authenticated using(user_id=auth.uid() and public.is_active()) with check(user_id=auth.uid() and public.is_active());
create policy bookmarks_own on public.bookmarks for all to authenticated using(user_id=auth.uid() and public.is_active()) with check(user_id=auth.uid() and public.is_active());
create policy providers_read on public.provider_configuration for select to authenticated using(public.is_admin());

create function public.review_entry(entry_id uuid,decision public.review_status,reason text) returns void language plpgsql security definer set search_path=public as $$
declare old_status public.review_status;
begin
 if not public.is_admin() then raise exception 'Administrator permission required'; end if;
 if length(trim(reason))<1 then raise exception 'Decision reason required'; end if;
 if decision='pending' then raise exception 'Invalid review decision'; end if;
 select status into old_status from public.entries where id=entry_id for update;
 if not found then raise exception 'Submission not found'; end if;
 if old_status=decision then raise exception 'Decision already applied'; end if;
 update public.entries set status=decision where id=entry_id;
 insert into public.audit_log(actor_id,entity_id,action,reason,details) values(auth.uid(),entry_id,'entry.'||decision,reason,jsonb_build_object('previous_status',old_status));
end $$;
revoke all on function public.review_entry(uuid,public.review_status,text) from public,anon;
grant execute on function public.review_entry(uuid,public.review_status,text) to authenticated;

-- Audited configuration editing. Finance remains server-only: no generic balance writes.
create function public.configure_plan(plan_id uuid,plan_name text,amount bigint,plan_currency text,plan_benefits jsonb,enabled boolean,reason text) returns uuid language plpgsql security definer set search_path=public as $$
declare result uuid;
begin
 if not public.is_admin() then raise exception 'Administrator permission required'; end if;
 if length(trim(reason))<1 then raise exception 'Reason required'; end if;
 insert into plans(id,name,price_minor,currency,benefits,active) values(coalesce(plan_id,gen_random_uuid()),plan_name,amount,plan_currency,plan_benefits,enabled)
 on conflict(id) do update set name=excluded.name,price_minor=excluded.price_minor,currency=excluded.currency,benefits=excluded.benefits,active=excluded.active returning id into result;
 insert into audit_log(actor_id,entity_id,action,reason) values(auth.uid(),result,'plan.configured',reason);return result;
end $$;
revoke all on function public.configure_plan(uuid,text,bigint,text,jsonb,boolean,text) from public,anon;
grant execute on function public.configure_plan(uuid,text,bigint,text,jsonb,boolean,text) to authenticated;

insert into storage.buckets(id,name,public,file_size_limit,allowed_mime_types) values('submissions','submissions',false,20971520,array['application/pdf','video/mp4','video/quicktime']);
create policy upload_private on storage.objects for insert to authenticated with check(bucket_id='submissions' and (storage.foldername(name))[1]=auth.uid()::text and public.is_active());
create policy read_submitted on storage.objects for select to authenticated using(bucket_id='submissions' and ((storage.foldername(name))[1]=auth.uid()::text or public.is_admin() or exists(select 1 from public.entries e where e.file_path=name and e.status='approved' and e.kind in ('book','course','reel'))));
-- No public storage URLs. Sensitive assistance/idea files stay private even after approval.

create function public.configure_platform(setting_kind text,setting jsonb,reason text) returns void language plpgsql security definer set search_path=public as $$
begin
 if not public.is_admin() then raise exception 'Administrator permission required'; end if;
 if length(trim(reason))<1 then raise exception 'Reason required'; end if;
 case setting_kind
 when 'feature' then
  insert into feature_rules(feature_key,access_mode) values(setting->>'feature_key',setting->>'access_mode') on conflict(feature_key) do update set access_mode=excluded.access_mode;
 when 'earnings' then
  if (setting->>'role') not in ('student','teacher','tutor','creator') then raise exception 'Invalid role'; end if;
  update earnings_policies set active=false where role=(setting->>'role')::user_role;
  insert into earnings_policies(role,view_rate,subscriber_rate,minimum_payout_minor,currency,active) values((setting->>'role')::user_role,(setting->>'view_rate')::numeric,(setting->>'subscriber_rate')::numeric,(setting->>'minimum_payout_minor')::bigint,setting->>'currency',true);
 when 'user' then
  if exists(select 1 from profiles where id=(setting->>'id')::uuid and role in ('admin','owner')) then raise exception 'Administrative accounts require owner review'; end if;
  update profiles set suspended=(setting->>'suspended')::boolean where id=(setting->>'id')::uuid;
 when 'report' then
  update reports set status=setting->>'status' where id=(setting->>'id')::uuid;
 else raise exception 'Unsupported configuration';
 end case;
 insert into audit_log(actor_id,action,reason,details) values(auth.uid(),'configuration.'||setting_kind,reason,setting);
end $$;
revoke all on function public.configure_platform(text,jsonb,text) from public,anon;
grant execute on function public.configure_platform(text,jsonb,text) to authenticated;


-- 002_learning_release.sql
-- 1.1.0: exact school grades, invitation classrooms, and private support.
-- Existing broad-level resources remain searchable; new resources require a grade.
create function public.validate_resource_grade() returns trigger language plpgsql set search_path=public as $$
begin
 if new.kind in ('book','course','reel') and new.level not in ('Grade 1','Grade 2','Grade 3','Grade 4','Grade 5','Grade 6','Grade 7','Form 1','Form 2','Form 3','Form 4','Form 5','Form 6') then raise exception 'Choose an exact resource grade'; end if;
 return new;
end $$;
create trigger resource_grade before insert on public.entries for each row execute function public.validate_resource_grade();
alter table public.entries add constraint video_attachment_required check(kind <> 'reel' or nullif(trim(file_path),'') is not null) not valid;
alter table public.profiles add column grade text check (grade in ('Grade 1','Grade 2','Grade 3','Grade 4','Grade 5','Grade 6','Grade 7','Form 1','Form 2','Form 3','Form 4','Form 5','Form 6'));
create or replace function public.create_profile() returns trigger language plpgsql security definer set search_path=public as $$
begin
 insert into profiles(id,grade) values(new.id, case when new.raw_user_meta_data->>'grade' in ('Grade 1','Grade 2','Grade 3','Grade 4','Grade 5','Grade 6','Grade 7','Form 1','Form 2','Form 3','Form 4','Form 5','Form 6') then new.raw_user_meta_data->>'grade' else null end);
 return new;
end $$;
-- Recover accounts registered before the application's tables were installed.
-- Metadata never assigns staff roles; every recovered profile starts as student.
insert into public.profiles(id,grade)
select id, case when raw_user_meta_data->>'grade' in ('Grade 1','Grade 2','Grade 3','Grade 4','Grade 5','Grade 6','Grade 7','Form 1','Form 2','Form 3','Form 4','Form 5','Form 6') then raw_user_meta_data->>'grade' else null end
from auth.users on conflict(id) do nothing;
create function public.set_my_grade(new_grade text) returns void language plpgsql security definer set search_path=public as $$
begin
 if not public.is_active() then raise exception 'Sign in with an active account'; end if;
 if new_grade is null then raise exception 'Choose your grade'; end if;
 update profiles set grade=new_grade where id=auth.uid();
end $$;
revoke all on function public.set_my_grade(text) from public,anon;
grant execute on function public.set_my_grade(text) to authenticated;

create table public.classrooms(id uuid primary key default gen_random_uuid(), owner_id uuid not null references public.profiles, title text not null check(length(trim(title)) between 4 and 120), grade text not null check(grade in ('Grade 1','Grade 2','Grade 3','Grade 4','Grade 5','Grade 6','Grade 7','Form 1','Form 2','Form 3','Form 4','Form 5','Form 6')), join_code text not null unique default replace(gen_random_uuid()::text,'-',''), created_at timestamptz not null default now());
create table public.classroom_members(classroom_id uuid references public.classrooms on delete cascade, user_id uuid references public.profiles on delete cascade, primary key(classroom_id,user_id));
create table public.classroom_lessons(classroom_id uuid references public.classrooms on delete cascade, entry_id uuid references public.entries on delete cascade, primary key(classroom_id,entry_id));
create function public.in_classroom(room_id uuid) returns boolean language sql stable security definer set search_path=public as $$ select public.is_active() and (public.is_admin() or exists(select 1 from classroom_members where classroom_id=room_id and user_id=auth.uid())) $$;
create function public.join_classroom(invite_code text) returns uuid language plpgsql security definer set search_path=public as $$
declare room_id uuid;
begin
 if not public.is_active() then raise exception 'Sign in with an active account'; end if;
 select id into room_id from classrooms where join_code=lower(trim(invite_code));
 if room_id is null then raise exception 'Invitation code not found. Ask your teacher for the full code.'; end if;
 insert into classroom_members values(room_id,auth.uid()) on conflict do nothing;
 return room_id;
end $$;
revoke all on function public.join_classroom(text), public.in_classroom(uuid) from public,anon;
grant execute on function public.join_classroom(text), public.in_classroom(uuid) to authenticated;
alter table public.classrooms enable row level security;
alter table public.classroom_members enable row level security;
alter table public.classroom_lessons enable row level security;
create policy rooms_read on public.classrooms for select to authenticated using(public.in_classroom(id));
create policy rooms_create on public.classrooms for insert to authenticated with check(public.is_admin() and owner_id=auth.uid());
create policy members_read on public.classroom_members for select to authenticated using(user_id=auth.uid() or public.is_admin());
create policy members_leave on public.classroom_members for delete to authenticated using(user_id=auth.uid());
create policy classroom_lessons_read on public.classroom_lessons for select to authenticated using(public.in_classroom(classroom_id));
create policy classroom_lessons_manage on public.classroom_lessons for all to authenticated using(public.is_admin()) with check(public.is_admin() and exists(select 1 from entries where id=entry_id and status='approved' and kind in ('book','course','reel')));

create table public.support_settings(id boolean primary key default true check(id), enabled boolean not null default false);
insert into public.support_settings default values;
create table public.support_requests(id uuid primary key default gen_random_uuid(), user_id uuid not null references public.profiles on delete cascade, message text not null check(length(trim(message)) between 10 and 4000), response text not null default '' check(length(response)<=4000), status text not null default 'open' check(status in ('open','answered','closed')), created_at timestamptz not null default now());
alter table public.support_settings enable row level security;
alter table public.support_requests enable row level security;
create policy support_settings_read on public.support_settings for select using(true);
create policy support_settings_manage on public.support_settings for update to authenticated using(public.is_admin()) with check(public.is_admin());
create policy support_read on public.support_requests for select to authenticated using(public.is_active() and (user_id=auth.uid() or public.is_admin()));
create policy support_submit on public.support_requests for insert to authenticated with check(user_id=auth.uid() and public.is_active() and status='open' and response='' and exists(select 1 from support_settings where enabled));
create function public.respond_to_support(request_id uuid, reply text, new_status text) returns void language plpgsql security definer set search_path=public as $$
begin
 if not public.is_admin() then raise exception 'Administrator permission required'; end if;
 if length(trim(reply))<1 or new_status not in ('answered','closed') then raise exception 'Add a response and valid status'; end if;
 update support_requests set response=trim(reply),status=new_status where id=request_id;
 if not found then raise exception 'Request not found'; end if;
 insert into audit_log(actor_id,entity_id,action,reason) values(auth.uid(),request_id,'support.'||new_status,'Private support response recorded');
end $$;
revoke all on function public.respond_to_support(uuid,text,text) from public,anon;
grant execute on function public.respond_to_support(uuid,text,text) to authenticated;
grant select on public.support_settings to anon,authenticated;
grant select,insert,delete on public.classrooms,public.classroom_members,public.classroom_lessons,public.support_requests to authenticated;
grant update on public.support_settings to authenticated;


-- 003_community.sql
-- Community features. Apply after 002 on existing installations.
alter table public.profiles add column first_name text not null default '', add column surname text not null default '', add column date_of_birth date, add column country text not null default '', add column account_type text not null default 'student' check(account_type in ('student','teacher')), add column moderator boolean not null default false;
create or replace function public.create_profile() returns trigger language plpgsql security definer set search_path=public as $$
begin
 insert into profiles(id,grade,first_name,surname,date_of_birth,country,account_type,display_name)
 values(new.id,case when new.raw_user_meta_data->>'grade' in ('Grade 1','Grade 2','Grade 3','Grade 4','Grade 5','Grade 6','Grade 7','Form 1','Form 2','Form 3','Form 4','Form 5','Form 6') then new.raw_user_meta_data->>'grade' end,
 coalesce(new.raw_user_meta_data->>'first_name',''),coalesce(new.raw_user_meta_data->>'surname',''),nullif(new.raw_user_meta_data->>'date_of_birth','')::date,coalesce(new.raw_user_meta_data->>'country',''),case when new.raw_user_meta_data->>'account_type'='teacher' then 'teacher' else 'student' end,coalesce(new.raw_user_meta_data->>'first_name','Learner'));
 return new;
end $$;
create function public.can_moderate() returns boolean language sql stable security definer set search_path=public as $$ select public.is_admin() or exists(select 1 from profiles where id=auth.uid() and moderator and not suspended) $$;
create function public.set_moderator(target_id uuid, enabled boolean) returns void language plpgsql security definer set search_path=public as $$ begin
 if not public.is_admin() then raise exception 'Administrator permission required'; end if;
 update profiles set moderator=enabled where id=target_id;
 insert into audit_log(actor_id,entity_id,action,reason) values(auth.uid(),target_id,'moderator.changed',enabled::text);
end $$;
create policy moderator_entries on public.entries for select to authenticated using(public.can_moderate());
create policy moderator_files on storage.objects for select to authenticated using(bucket_id='submissions' and public.can_moderate());
create or replace function public.review_entry(entry_id uuid,decision public.review_status,reason text) returns void language plpgsql security definer set search_path=public as $$
declare old_status public.review_status;
begin
 if not public.can_moderate() then raise exception 'Administrator permission required'; end if;
 if length(trim(reason))<1 then raise exception 'Decision reason required'; end if;
 if decision='pending' then raise exception 'Invalid review decision'; end if;
 select status into old_status from entries where id=entry_id for update;
 if not found then raise exception 'Submission not found'; end if;
 if old_status=decision then raise exception 'Decision already applied'; end if;
 update entries set status=decision where id=entry_id;
 insert into audit_log(actor_id,entity_id,action,reason) values(auth.uid(),entry_id,'entry.'||decision,reason);
end $$;
alter table public.entries add column video_format text not null default 'lesson' check(video_format in ('lesson','talent'));
create function public.publish_talent() returns trigger language plpgsql set search_path=public as $$ begin
 if new.kind='reel' and new.video_format='talent' then new.status='approved'; end if; return new;
end $$;
create trigger publish_talent before insert on public.entries for each row execute function public.publish_talent();
drop policy entries_submit on public.entries;
create policy entries_submit on public.entries for insert to authenticated with check(owner_id=auth.uid() and public.is_active() and (status='pending' or (kind='reel' and video_format='talent' and status='approved')) and target=0 and raised=0 and (file_path is null or file_path like auth.uid()::text||'/%'));
create table public.notifications(id uuid primary key default gen_random_uuid(), user_id uuid not null references profiles on delete cascade, message text not null, read boolean not null default false, created_at timestamptz not null default now());
alter table public.notifications enable row level security;
create policy notifications_read on public.notifications for select to authenticated using(user_id=auth.uid() and public.is_active());
create policy notifications_update on public.notifications for update to authenticated using(user_id=auth.uid() and public.is_active()) with check(user_id=auth.uid());
grant select on public.notifications to authenticated;
revoke update on public.notifications from anon,authenticated;
grant update(read) on public.notifications to authenticated;
create function public.notify_review() returns trigger language plpgsql security definer set search_path=public as $$ begin
 if old.status<>new.status then insert into notifications(user_id,message) values(new.owner_id,new.title||': '||new.status); end if; return new;
end $$;
create trigger notify_review after update of status on entries for each row execute function public.notify_review();
create function public.notify_support() returns trigger language plpgsql security definer set search_path=public as $$ begin
 if new.response<>old.response then insert into notifications(user_id,message) values(new.user_id,'You have a private Safe Room reply. Open Safe Room to read it.'); end if; return new;
end $$;
create trigger notify_support after update on support_requests for each row execute function public.notify_support();
create table public.video_likes(entry_id uuid references entries on delete cascade,user_id uuid references profiles on delete cascade,primary key(entry_id,user_id));
create table public.video_comments(id uuid primary key default gen_random_uuid(),entry_id uuid not null references entries on delete cascade,user_id uuid not null references profiles on delete cascade,body text not null check(length(trim(body)) between 1 and 1000),created_at timestamptz not null default now());
alter table public.video_likes enable row level security;
alter table public.video_comments enable row level security;
create policy likes_read on video_likes for select to authenticated using(exists(select 1 from entries where id=entry_id and status='approved'));
create policy likes_insert on video_likes for insert to authenticated with check(user_id=auth.uid() and public.is_active() and exists(select 1 from entries where id=entry_id and status='approved' and kind='reel'));
create policy likes_delete on video_likes for delete to authenticated using(user_id=auth.uid());
create policy comments_read on video_comments for select to authenticated using(exists(select 1 from entries where id=entry_id and status='approved'));
create policy comments_insert on video_comments for insert to authenticated with check(user_id=auth.uid() and public.is_active() and exists(select 1 from entries where id=entry_id and status='approved' and kind='reel'));
create policy comments_delete on video_comments for delete to authenticated using(user_id=auth.uid() or public.can_moderate());
grant select,insert,delete on video_likes,video_comments to authenticated;
create table public.quiz_questions(id integer generated by default as identity primary key,subject text not null,prompt text not null,choices jsonb not null,answer integer not null,explanation text not null);
create table public.quiz_answers(user_id uuid references profiles on delete cascade,question_id integer references quiz_questions,choice integer not null,points integer not null,primary key(user_id,question_id));
alter table quiz_questions enable row level security;
alter table quiz_answers enable row level security;
create policy questions_read on quiz_questions for select using(true);
revoke select on quiz_questions from anon,authenticated;
grant select(id,subject,prompt,choices) on quiz_questions to anon,authenticated;
create policy answers_read on quiz_answers for select to authenticated using(user_id=auth.uid());
grant select on quiz_answers to authenticated;
create function public.answer_quiz(question integer,selected integer) returns jsonb language plpgsql security definer set search_path=public as $$
declare q quiz_questions; earned integer; begin
 if not public.is_active() then raise exception 'Sign in to earn Guru Student points'; end if;
 select * into q from quiz_questions where id=question;
 if not found or selected<0 or selected>=jsonb_array_length(q.choices) then raise exception 'Invalid question or answer'; end if;
 earned:=case when q.answer=selected then 10 else 0 end;
 insert into quiz_answers values(auth.uid(),question,selected,earned);
 return jsonb_build_object('points',earned,'explanation',q.explanation);
end $$;
create function public.quiz_leaderboard() returns table(learner text,points bigint) language sql stable security definer set search_path=public as $$
 select coalesce(nullif(p.display_name,''),'Learner')||' · '||left(p.id::text,6),sum(a.points) from quiz_answers a join profiles p on p.id=a.user_id where not p.suspended group by p.id order by sum(a.points) desc,p.id
$$;
insert into quiz_questions(subject,prompt,choices,answer,explanation) values
('Maths','What is 12 × 8?','["80","96","108"]',1,'12 multiplied by 8 is 96.'),
('Maths','What is a quarter of 100?','["20","25","50"]',1,'100 divided by 4 is 25.'),
('Maths','Solve x + 7 = 15.','["7","8","22"]',1,'Subtract 7 from both sides: x = 8.'),
('Maths','Area of a rectangle 6 cm by 4 cm?','["10 cm²","20 cm²","24 cm²"]',2,'Area = length × width = 24 cm².'),
('Science','Which gas do plants absorb during photosynthesis?','["Oxygen","Carbon dioxide","Hydrogen"]',1,'Plants use carbon dioxide and water to make sugars.'),
('Science','Which organ pumps blood?','["Heart","Lung","Kidney"]',0,'The heart pumps blood through the body.'),
('Science','What is the chemical formula for water?','["CO2","H2O","O2"]',1,'Water contains two hydrogen atoms and one oxygen atom.'),
('Science','Which planet is closest to the Sun?','["Earth","Mars","Mercury"]',2,'Mercury is the closest planet to the Sun.'),
('General knowledge','How many days are in a leap year?','["364","365","366"]',2,'A leap year includes 29 February, giving 366 days.'),
('General knowledge','Which is the largest ocean?','["Atlantic","Pacific","Indian"]',1,'The Pacific is the largest ocean.'),
('General knowledge','On which continent is Zimbabwe?','["Africa","Asia","Europe"]',0,'Zimbabwe is in southern Africa.'),
('General knowledge','How many sides does a hexagon have?','["5","6","8"]',1,'A hexagon has six sides.');
create policy published_rates on earnings_policies for select using(active);
grant select on earnings_policies to anon,authenticated;
revoke all on function public.can_moderate(),public.set_moderator(uuid,boolean),public.answer_quiz(integer,integer),public.quiz_leaderboard() from public,anon;
grant execute on function public.can_moderate(),public.set_moderator(uuid,boolean),public.answer_quiz(integer,integer),public.quiz_leaderboard() to authenticated;
alter table classrooms add column price_minor integer not null default 0 check(price_minor between 0 and 10000000), add column currency text not null default 'USD' check(currency='USD');
create policy owned_rooms_read on classrooms for select to authenticated using(owner_id=auth.uid() and public.is_active());
drop policy rooms_create on classrooms;
create policy rooms_create on classrooms for insert to authenticated with check(owner_id=auth.uid() and public.is_active());
create or replace function public.in_classroom(room_id uuid) returns boolean language sql stable security definer set search_path=public as $$ select public.is_active() and (public.is_admin() or exists(select 1 from classrooms where id=room_id and owner_id=auth.uid()) or exists(select 1 from classroom_members where classroom_id=room_id and user_id=auth.uid())) $$;
create or replace function public.join_classroom(invite_code text) returns uuid language plpgsql security definer set search_path=public as $$
declare room classrooms;
begin
 if not public.is_active() then raise exception 'Sign in with an active account'; end if;
 select * into room from classrooms where join_code=lower(trim(invite_code));
 if not found then raise exception 'Invitation code not found. Ask your teacher for the full code.'; end if;
 if room.price_minor>0 and room.owner_id<>auth.uid() then raise exception 'Paid enrolment is not available until verified payments are connected.'; end if;
 insert into classroom_members values(room.id,auth.uid()) on conflict do nothing;
 return room.id;
end $$;
create policy owner_lessons_manage on classroom_lessons for all to authenticated using(public.is_active() and exists(select 1 from classrooms where id=classroom_id and owner_id=auth.uid())) with check(public.is_active() and exists(select 1 from classrooms where id=classroom_id and owner_id=auth.uid()) and exists(select 1 from entries where id=entry_id and status='approved' and kind in ('book','course','reel')));


-- 004_services.sql
-- Push, verified purchases, classroom access and creator accounting.
create table public.push_devices(token text primary key check(token ~ '^(ExponentPushToken|ExpoPushToken)\[[A-Za-z0-9_-]+\]$'), user_id uuid not null references profiles on delete cascade, updated_at timestamptz not null default now());
create table public.push_jobs(id uuid primary key default gen_random_uuid(), notification_id uuid not null references notifications on delete cascade, token text not null references push_devices on delete cascade, user_id uuid not null references profiles on delete cascade, status text not null default 'pending' check(status in ('pending','sending','receipt','delivered','failed')), attempts integer not null default 0, ticket_id text, next_attempt timestamptz not null default now(), last_error text, unique(notification_id,token));
alter table push_devices enable row level security;
alter table push_jobs enable row level security;
revoke all on push_devices,push_jobs from anon,authenticated;
grant all on push_devices,push_jobs to service_role;
create function register_push(device_token text) returns void language plpgsql security definer set search_path=public as $$ begin
 if not is_active() then raise exception 'Sign in with an active account'; end if;
 insert into push_devices(token,user_id) values(device_token,auth.uid()) on conflict(token) do update set user_id=excluded.user_id,updated_at=now();
 update push_jobs set status='failed',last_error='Device reassigned' where token=device_token and user_id<>auth.uid() and status in ('pending','sending','receipt');
end $$;
create function unregister_push(device_token text) returns void language sql security definer set search_path=public as $$ delete from push_devices where token=device_token and user_id=auth.uid() $$;
create function enqueue_push() returns trigger language plpgsql security definer set search_path=public as $$ begin
 insert into push_jobs(notification_id,token,user_id) select new.id,token,new.user_id from push_devices where user_id=new.user_id;
 return new;
end $$;
create trigger enqueue_push after insert on notifications for each row execute function enqueue_push();
create function claim_push_jobs() returns setof push_jobs language sql security definer set search_path=public as $$
 update push_jobs set status=case when ticket_id is null then 'sending' else 'receipt' end,attempts=attempts+1,next_attempt=now()+interval '5 minutes'
 where id in (select j.id from push_jobs j join push_devices d on d.token=j.token and d.user_id=j.user_id join profiles p on p.id=j.user_id and not p.suspended where j.status in ('pending','sending','receipt') and j.attempts<8 and j.next_attempt<=now() order by j.next_attempt for update of j skip locked limit 50) returning *
$$;

create table public.store_products(product_id text primary key, entitlement_id text not null unique, classroom_id uuid unique references classrooms on delete cascade, active boolean not null default true);
insert into store_products(product_id,entitlement_id) values('remove_ads','remove_ads');
create table public.purchase_access(user_id uuid references profiles on delete cascade,product_id text references store_products,expires_at timestamptz,verified_at timestamptz not null default now(),primary key(user_id,product_id));
create table public.purchase_sync(user_id uuid primary key references profiles on delete cascade,checked_at timestamptz not null);
alter table store_products enable row level security;
alter table purchase_access enable row level security;
alter table purchase_sync enable row level security;
create policy products_read on store_products for select using(active or is_admin());
create policy products_manage on store_products for all to authenticated using(is_admin()) with check(is_admin());
create policy access_read on purchase_access for select to authenticated using(user_id=auth.uid() and is_active());
grant select on store_products to anon,authenticated;
grant insert,update,delete on store_products to authenticated;
grant select on purchase_access to authenticated;
revoke all on purchase_sync from anon,authenticated;
grant all on store_products,purchase_access,purchase_sync to service_role;
create function sync_purchase_access(target_user uuid, snapshot jsonb, checked timestamptz) returns void language plpgsql security definer set search_path=public as $$ begin
 perform pg_advisory_xact_lock(hashtextextended(target_user::text,1));
 if exists(select 1 from purchase_sync where user_id=target_user and checked_at>checked) then return; end if;
 delete from purchase_access where user_id=target_user;
 insert into purchase_access(user_id,product_id,expires_at,verified_at) select target_user,p.product_id,nullif(v->>'expires_at','')::timestamptz,checked from jsonb_array_elements(snapshot) v join store_products p on p.product_id=v->>'product_id' and p.active where nullif(v->>'expires_at','') is null or (v->>'expires_at')::timestamptz>now();
 insert into purchase_sync values(target_user,checked) on conflict(user_id) do update set checked_at=excluded.checked_at;
end $$;
create function has_classroom_access(room_id uuid) returns boolean language sql stable security definer set search_path=public as $$
 select is_active() and (is_admin() or exists(select 1 from classrooms where id=room_id and owner_id=auth.uid()) or exists(select 1 from purchase_access a join store_products p using(product_id) where a.user_id=auth.uid() and p.classroom_id=room_id and p.active and (a.expires_at is null or a.expires_at>now())))
$$;
create or replace function in_classroom(room_id uuid) returns boolean language sql stable security definer set search_path=public as $$
 select is_active() and (is_admin() or exists(select 1 from classrooms where id=room_id and owner_id=auth.uid()) or exists(select 1 from classroom_members m join classrooms c on c.id=m.classroom_id where c.id=room_id and m.user_id=auth.uid() and (c.price_minor=0 or has_classroom_access(room_id))))
$$;
create function classroom_offer(invite_code text) returns table(id uuid,title text,price_minor integer,currency text,product_id text) language sql stable security definer set search_path=public as $$
 select c.id,c.title,c.price_minor,c.currency,p.product_id from classrooms c left join store_products p on p.classroom_id=c.id and p.active where is_active() and c.join_code=lower(trim(invite_code))
$$;
create or replace function join_classroom(invite_code text) returns uuid language plpgsql security definer set search_path=public as $$ declare room classrooms; begin
 if not is_active() then raise exception 'Sign in with an active account'; end if;
 select * into room from classrooms where join_code=lower(trim(invite_code));
 if not found then raise exception 'Invitation code not found. Ask your teacher for the full code.'; end if;
 if room.price_minor>0 and room.owner_id<>auth.uid() and not has_classroom_access(room.id) then raise exception 'Complete a verified purchase before joining this classroom'; end if;
 insert into classroom_members values(room.id,auth.uid()) on conflict do nothing; return room.id;
end $$;

-- Timed usage is evidence pending review, never a client-authorized cash credit.
create table public.content_usage(id uuid primary key default gen_random_uuid(),entry_id uuid not null references entries on delete cascade,viewer_id uuid not null references profiles on delete cascade,day date not null default current_date,started_at timestamptz not null default now(),last_seen timestamptz not null default now(),seconds integer not null default 0,policy_id uuid references earnings_policies,rate numeric(16,8) not null default 0,currency text not null default 'USD',status text not null default 'tracking' check(status in ('tracking','qualified','approved','rejected')),unique(entry_id,viewer_id,day));
create table public.creator_ledger(id uuid primary key default gen_random_uuid(),user_id uuid not null references profiles,usage_id uuid unique references content_usage,amount numeric(20,8) not null check(amount>0),currency text not null,created_at timestamptz not null default now());
create table public.payout_accounts(user_id uuid primary key references profiles on delete cascade,stripe_account text unique not null,created_at timestamptz not null default now());
create table public.payout_requests(id uuid primary key default gen_random_uuid(),user_id uuid not null references profiles,amount_minor bigint not null check(amount_minor>0),currency text not null,status text not null default 'requested' check(status in ('requested','processing','transferred','failed','cancelled')),provider_reference text unique,last_error text,created_at timestamptz not null default now());
alter table content_usage enable row level security;
alter table creator_ledger enable row level security;
alter table payout_accounts enable row level security;
alter table payout_requests enable row level security;
create policy usage_admin on content_usage for select to authenticated using(is_admin());
create policy ledger_read on creator_ledger for select to authenticated using(user_id=auth.uid() or is_admin());
create policy payouts_read on payout_requests for select to authenticated using(user_id=auth.uid() or is_admin());
create policy account_read on payout_accounts for select to authenticated using(user_id=auth.uid());
grant select on content_usage,creator_ledger,payout_accounts,payout_requests to authenticated;
grant all on content_usage,creator_ledger,payout_accounts,payout_requests to service_role;
create function begin_content_usage(content_id uuid) returns uuid language plpgsql security definer set search_path=public as $$ declare item entries; policy earnings_policies; usage_id uuid; begin
 if not is_active() then return null; end if;
 select * into item from entries where id=content_id and status='approved' and kind in ('book','course','reel');
 if not found or item.owner_id=auth.uid() then return null; end if;
 if (select count(*) from content_usage where viewer_id=auth.uid() and day=current_date)>=100 then return null; end if;
 select ep.* into policy from earnings_policies ep join profiles p on p.id=item.owner_id where ep.active and ep.role=(case when p.account_type='teacher' then 'teacher' else p.role::text end)::user_role order by ep.id limit 1;
 insert into content_usage(entry_id,viewer_id,policy_id,rate,currency) values(content_id,auth.uid(),policy.id,coalesce(policy.view_rate,0),coalesce(policy.currency,'USD')) on conflict(entry_id,viewer_id,day) do nothing returning id into usage_id;
 if usage_id is null then update content_usage set last_seen=now() where entry_id=content_id and viewer_id=auth.uid() and day=current_date returning id into usage_id; end if;
 return usage_id;
end $$;
create function heartbeat_content_usage(usage_id uuid) returns void language plpgsql security definer set search_path=public as $$ declare elapsed integer; item content_usage; begin
 if not is_active() then return; end if;
 select * into item from content_usage where id=usage_id and viewer_id=auth.uid() and status='tracking' for update;
 if not found then return; end if;
 elapsed:=floor(extract(epoch from now()-item.last_seen));
 -- Long gaps do not count as active reading/playback; calls cannot accelerate time.
 update content_usage set seconds=seconds+case when elapsed between 8 and 25 then elapsed else 0 end,last_seen=now(),status=case when seconds+case when elapsed between 8 and 25 then elapsed else 0 end>=30 then 'qualified' else 'tracking' end where id=usage_id;
end $$;
create function review_usage(usage_id uuid,approve boolean,reason text) returns void language plpgsql security definer set search_path=public as $$ declare item content_usage; owner uuid; begin
 if not is_admin() then raise exception 'Administrator permission required'; end if;
 if length(trim(reason))<5 then raise exception 'Explain the activity review'; end if;
 select * into item from content_usage where id=usage_id and status='qualified' for update;
 if not found then raise exception 'Qualified activity not found'; end if;
 select owner_id into owner from entries where id=item.entry_id and status='approved';
 if approve and (owner is null or item.rate<=0) then raise exception 'Published content and a positive rate are required'; end if;
 if approve then insert into creator_ledger(user_id,usage_id,amount,currency) values(owner,item.id,item.rate,item.currency); end if;
 update content_usage set status=case when approve then 'approved' else 'rejected' end where id=item.id;
 insert into audit_log(actor_id,entity_id,action,reason) values(auth.uid(),item.id,case when approve then 'usage.approved' else 'usage.rejected' end,reason);
end $$;
create function request_creator_payout(payout_currency text) returns uuid language plpgsql security definer set search_path=public as $$ declare available bigint; threshold bigint; result uuid; begin
 if not is_active() then raise exception 'Sign in with an active account'; end if;
 if payout_currency not in ('USD','EUR','GBP','ZAR') then raise exception 'Payout currency is not supported'; end if;
 perform pg_advisory_xact_lock(hashtextextended(auth.uid()::text,2));
 select floor(coalesce(sum(amount),0)*100)::bigint into available from creator_ledger where user_id=auth.uid() and currency=payout_currency;
 available:=available-coalesce((select sum(amount_minor) from payout_requests where user_id=auth.uid() and currency=payout_currency and status in ('requested','processing','transferred')),0);
 select ep.minimum_payout_minor into threshold from earnings_policies ep join profiles p on p.id=auth.uid() where ep.active and ep.currency=payout_currency and ep.role=(case when p.account_type='teacher' then 'teacher' else p.role::text end)::user_role order by ep.id limit 1;
 if available<greatest(coalesce(threshold,1000),1) then raise exception 'Available balance is below the payout minimum'; end if;
 if not exists(select 1 from payout_accounts where user_id=auth.uid()) then raise exception 'Complete payout account setup first'; end if;
 insert into payout_requests(user_id,amount_minor,currency) values(auth.uid(),available,payout_currency) returning id into result;
 return result;
end $$;
alter table payout_requests add column attempted_at timestamptz;
create function claim_payout(request_id uuid) returns setof payout_requests language sql security definer set search_path=public as $$ update payout_requests set status='processing',last_error=null,attempted_at=coalesce(attempted_at,now()) where id=request_id and status in ('requested','processing') and (attempted_at is null or attempted_at>now()-interval '23 hours') returning * $$;

revoke all on function register_push(text),unregister_push(text),claim_push_jobs(),sync_purchase_access(uuid,jsonb,timestamptz),has_classroom_access(uuid),classroom_offer(text),begin_content_usage(uuid),heartbeat_content_usage(uuid),review_usage(uuid,boolean,text),request_creator_payout(text),claim_payout(uuid) from public,anon,authenticated;
grant execute on function register_push(text),unregister_push(text),has_classroom_access(uuid),classroom_offer(text),begin_content_usage(uuid),heartbeat_content_usage(uuid),review_usage(uuid,boolean,text),request_creator_payout(text) to authenticated;
grant execute on function claim_push_jobs(),sync_purchase_access(uuid,jsonb,timestamptz),claim_payout(uuid) to service_role;
create function creator_summary() returns table(currency text,earned numeric,pending numeric,available numeric) language sql stable security definer set search_path=public as $$
 with currencies as (select l.currency from creator_ledger l where l.user_id=auth.uid() union select u.currency from content_usage u join entries e on e.id=u.entry_id where e.owner_id=auth.uid())
 select c.currency,coalesce((select sum(l.amount) from creator_ledger l where l.user_id=auth.uid() and l.currency=c.currency),0),coalesce((select sum(u.rate) from content_usage u join entries e on e.id=u.entry_id where e.owner_id=auth.uid() and u.currency=c.currency and u.status='qualified'),0),greatest(0,floor(coalesce((select sum(l.amount) from creator_ledger l where l.user_id=auth.uid() and l.currency=c.currency),0)*100)/100-coalesce((select sum(p.amount_minor)/100.0 from payout_requests p where p.user_id=auth.uid() and p.currency=c.currency and p.status in ('requested','processing','transferred')),0)) from currencies c where is_active()
$$;
create function save_store_product(product text,entitlement text,room uuid,reason text) returns void language plpgsql security definer set search_path=public as $$ begin
 if not is_admin() then raise exception 'Administrator permission required'; end if;
 if length(trim(reason))<5 or length(trim(product))<3 or length(trim(entitlement))<3 then raise exception 'Product, entitlement and review reason required'; end if;
 if room is null and entitlement<>'remove_ads' then raise exception 'Non-classroom products must use remove_ads entitlement'; end if;
 insert into store_products(product_id,entitlement_id,classroom_id) values(product,entitlement,room) on conflict(product_id) do update set entitlement_id=excluded.entitlement_id,classroom_id=excluded.classroom_id;
 insert into audit_log(actor_id,action,reason,details) values(auth.uid(),'store.product',reason,jsonb_build_object('product',product,'classroom',room));
end $$;
revoke all on function creator_summary(),save_store_product(text,text,uuid,text) from public,anon;
grant execute on function creator_summary(),save_store_product(text,text,uuid,text) to authenticated;


notify pgrst, 'reload schema';
commit;
